# Generated by Django 4.0.6 on 2022-08-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine_day',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day', to='routine_app.routine'),
        ),
        migrations.AlterField(
            model_name='routine_result',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_result', to='routine_app.routine'),
        ),
    ]
