# Generated by Django 4.0.6 on 2022-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0002_alter_routine_day_routine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
